import discord
from discord.ext import commands
import requests

class Roulette(commands.Cog):

    def __init__(self, client):
        self.client = client

    @commands.command(name="r6roulette", aliases=["strat"], description="A r6 strat roulette command generated by https://squadstrats.com/")
    async def _strat_roulette(self, ctx, gamemode, *, team):
        r = requests.get(f"https://squadstrats.com/api/?type={gamemode.lower()}&team={team.lower()}")

        if r.status_code != 200:
            return await ctx.send("<https://squadstrats.com/> can not be resolved.")

        if r.text == ": ":
            error = discord.Embed(title="Error", description="Bad Argument | usage: r6roulette <gamemode> <team>", colour=discord.Colour.default(), timestamp=ctx.message.created_at)
            error.add_field(name="Gamemodes:", value="bomb/hostage/secure", inline=False)
            error.add_field(name="Teams:", value="attack/defend", inline=False)
            error.set_thumbnail(url="https://lh3.googleusercontent.com/SngkeOw_CeWAeS2ityYforTJvDE5HmftlsKPnmwLaDofjSEvopkvPSNIVI67OzzSuGM")
            error.set_footer(text="<> = required, [] = optional", icon_url="https://lh3.googleusercontent.com/SngkeOw_CeWAeS2ityYforTJvDE5HmftlsKPnmwLaDofjSEvopkvPSNIVI67OzzSuGM")

            return await ctx.send(embed=error)

        title, description = r.text.split(": ")

        embed = discord.Embed(title=title, description=description, colour=discord.Colour.default(), timestamp=ctx.message.created_at)
        embed.set_thumbnail(url="https://lh3.googleusercontent.com/SngkeOw_CeWAeS2ityYforTJvDE5HmftlsKPnmwLaDofjSEvopkvPSNIVI67OzzSuGM")
        embed.set_footer(text="Generated by https://squadstrats.com/", icon_url="https://lh3.googleusercontent.com/SngkeOw_CeWAeS2ityYforTJvDE5HmftlsKPnmwLaDofjSEvopkvPSNIVI67OzzSuGM")

        await ctx.send(embed=embed)

def setup(client):
    client.add_cog(Roulette(client))